# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codaprouv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codillon',
            name='nom',
            field=models.CharField(default='Test', max_length=30),
            preserve_default=False,
        ),
    ]
